CREATE TABLE FAA.al_perf (
  `Year` int(11) DEFAULT NULL,
  `Quarter` int(11) DEFAULT NULL,
  `Month` int(11) DEFAULT NULL,
  `DayofMonth` int(11) DEFAULT NULL,
  `DayOfWeek` int(11) DEFAULT NULL,
  `FlightDate` text,
  `Reporting_Airline` text,
  `DOT_ID_Reporting_Airline` int(11) DEFAULT NULL,
  `IATA_CODE_Reporting_Airline` text,
  `Tail_Number` text,
  `Flight_Number_Reporting_Airline` int(11) DEFAULT NULL,
  `OriginAirportID` int(11) DEFAULT NULL,
  `OriginAirportSeqID` int(11) DEFAULT NULL,
  `OriginCityMarketID` int(11) DEFAULT NULL,
  `Origin` text,
  `OriginCityName` text,
  `OriginState` text,
  `OriginStateFips` int(11) DEFAULT NULL,
  `OriginStateName` text,
  `OriginWac` int(11) DEFAULT NULL,
  `DestAirportID` int(11) DEFAULT NULL,
  `DestAirportSeqID` int(11) DEFAULT NULL,
  `DestCityMarketID` int(11) DEFAULT NULL,
  `Dest` text,
  `DestCityName` text,
  `DestState` text,
  `DestStateFips` int(11) DEFAULT NULL,
  `DestStateName` text,
  `DestWac` int(11) DEFAULT NULL,
  `CRSDepTime` text,
  `DepTime` text,
  `DepDelay` decimal(11,0) DEFAULT NULL,
  `DepDelayMinutes` double DEFAULT NULL,
  `DepDel15` double DEFAULT NULL,
  `DepartureDelayGroups` int(11) DEFAULT NULL,
  `DepTimeBlk` text,
  `TaxiOut` double DEFAULT NULL,
  `WheelsOff` text,
  `WheelsOn` text,
  `TaxiIn` double DEFAULT NULL,
  `CRSArrTime` text,
  `ArrTime` text,
  `ArrDelay` double DEFAULT NULL,
  `ArrDelayMinutes` double DEFAULT NULL,
  `ArrDel15` double DEFAULT NULL,
  `ArrivalDelayGroups` int(11) DEFAULT NULL,
  `ArrTimeBlk` text,
  `Cancelled` double DEFAULT NULL,
  `CancellationCode` text,
  `Diverted` double DEFAULT NULL,
  `CRSElapsedTime` double DEFAULT NULL,
  `ActualElapsedTime` double DEFAULT NULL,
  `AirTime` double DEFAULT NULL,
  `Flights` double DEFAULT NULL,
  `Distance` double DEFAULT NULL,
  `DistanceGroup` int(11) DEFAULT NULL,
  `CarrierDelay` text,
  `WeatherDelay` text,
  `NASDelay` text,
  `SecurityDelay` text,
  `LateAircraftDelay` text,
  `FirstDepTime` text,
  `TotalAddGTime` text,
  `LongestAddGTime` text,
  `DivAirportLandings` int(11) DEFAULT NULL,
  `DivReachedDest` text,
  `DivActualElapsedTime` text,
  `DivArrDelay` text,
  `DivDistance` text,
  `Div1Airport` text,
  `Div1AirportID` text,
  `Div1AirportSeqID` text,
  `Div1WheelsOn` text,
  `Div1TotalGTime` text,
  `Div1LongestGTime` text,
  `Div1WheelsOff` text,
  `Div1TailNum` text,
  `Div2Airport` text,
  `Div2AirportID` text,
  `Div2AirportSeqID` text,
  `Div2WheelsOn` text,
  `Div2TotalGTime` text,
  `Div2LongestGTime` text,
  `Div2WheelsOff` text,
  `Div2TailNum` text,
  `Div3Airport` text,
  `Div3AirportID` text,
  `Div3AirportSeqID` text,
  `Div3WheelsOn` text,
  `Div3TotalGTime` text,
  `Div3LongestGTime` text,
  `Div3WheelsOff` text,
  `Div3TailNum` text,
  `Div4Airport` text,
  `Div4AirportID` text,
  `Div4AirportSeqID` text,
  `Div4WheelsOn` text,
  `Div4TotalGTime` text,
  `Div4LongestGTime` text,
  `Div4WheelsOff` text,
  `Div4TailNum` text,
  `Div5Airport` text,
  `Div5AirportID` text,
  `Div5AirportSeqID` text,
  `Div5WheelsOn` text,
  `Div5TotalGTime` text,
  `Div5LongestGTime` text,
  `Div5WheelsOff` text,
  `Div5TailNum` text,
  `MyUnknownColumn` text
) ;


